# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'constrainTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!


  # Pods for constrainTest
 pod 'Firebase/Core'
 pod 'Firebase/Database'
 pod 'Firebase/Storage'
 pod 'Firebase/Messaging'
 pod 'Firebase/Auth'
 pod 'Firebase/Firestore’
 pod 'ActiveLabel'

end
